
SET(CMAKE_CXX_STANDARD 17)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)
SET(CMAKE_CXX_EXTENSIONS OFF)
SET(toolkit-clientdb_VERSION_STAGE "beta")
CONFIGURE_FILE("${PROJECT_SOURCE_DIR}/config.h.in" "${PROJECT_SOURCE_DIR}/config.h")


FIND_PACKAGE(common-c++ REQUIRED PATHS ${PROJECT_SOURCE_DIR}/../cmake/Modules/toolkit/)
IF(TOOLKIT_COMMON_FOUND)
   INCLUDE_DIRECTORIES(${TOOLKIT_COMMON_INCLUDE_DIR})
ELSE()
        MESSAGE(FATAL_ERROR "No se encontro toolkit-common.")
ENDIF()
IF(NOT SERVER)
	MESSAGE(FATAL_ERROR "Use la variable SERVER para indicar el el typo de base de datos.")
ELSEIF(${SERVER} STREQUAL "MYSQL")
	MESSAGE("El Servidor seleccionado es MySQL ...")
	FIND_PACKAGE(MySQL REQUIRED PATHS ${PROJECT_SOURCE_DIR}/../cmake/Modules/)
	IF(MySQL_FOUND)
	   INCLUDE_DIRECTORIES(${MYSQL_INCLUDE_DIR})
	ENDIF()
	ADD_EXECUTABLE(developing clientdb.cpp clientdb-mysql.cpp developing.cpp)
	TARGET_LINK_LIBRARIES(developing ${TOOLKIT_COMMON_LIBRARY} ${MYSQL_LIBRARY} )
	ADD_LIBRARY(myc++ STATIC clientdb.cpp clientdb-mysql.cpp)
	TARGET_LINK_LIBRARIES(myc++ ${TOOLKIT_COMMON_LIBRARY} ${MYSQL_LIBRARY} ${DWARF_LIBRARY})
	INSTALL(TARGETS myc++ DESTINATION lib/toolkit/clientdb)
	INSTALL(FILES clientdb.hpp DESTINATION include/toolkit/clientdb)
	INSTALL(FILES clientdb-mysql.hpp DESTINATION include/toolkit/clientdb)
	SET(CPACK_PACKAGE_NAME "${PROJECT_NAME}-myc++")
ELSEIF(${SERVER} STREQUAL "POSTGRESQL")
	MESSAGE("El Servidor seleccionado es PostgreSQL ...")
	FIND_PACKAGE(PostgreSQL REQUIRED PATHS ${PROJECT_SOURCE_DIR}/../cmake/Modules/)
	IF(PostgreSQL_FOUND)
		INCLUDE_DIRECTORIES(${POSTGRESQL_INCLUDE_DIR})
	ENDIF()
	ADD_EXECUTABLE(postgresql clientdb.cpp clientdb-postgresql.cpp postgresql.cpp)
	TARGET_LINK_LIBRARIES(postgresql ${TOOLKIT_COMMON_LIBRARY} ${POSTGRESQL_LIBRARIES} )
	ADD_LIBRARY(toolkit-clientdb-c++-postgresql STATIC clientdb.cpp clientdb-postgresql.cpp)
	TARGET_LINK_LIBRARIES(postgresql-c++ ${TOOLKIT_COMMON_LIBRARY} ${POSTGRESQL_LIBRARIES} )
	INSTALL(TARGETS postgresql-c++ DESTINATION lib/toolkit/clientdb)
	INSTALL(FILES clientdb.hpp DESTINATION include/toolkit/clientdb)
	INSTALL(FILES clientdb-postgresql.hpp DESTINATION include/toolkit/clientdb)
	SET(CPACK_PACKAGE_NAME "${PROJECT_NAME}-pqc++")
ENDIF()
