#SET(CMAKE_C_COMPILER /usr/bin/gcc-7 CACHE PATH "" FORCE)
#SET(CMAKE_CXX_COMPILER /usr/bin/g++-7 CACHE PATH "" FORCE)
ENABLE_LANGUAGE(C)

SET(CMAKE_C_STANDARD 11)
SET(CMAKE_C_STANDARD_REQUIRED ON)
SET(CMAKE_C_EXTENSIONS OFF)
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")

SET(toolkit-common_VERSION_STAGE "alpha")
configure_file ("${PROJECT_SOURCE_DIR}/config.h.in" "${PROJECT_SOURCE_DIR}/config.h")

ADD_EXECUTABLE(main main.c common.c)
ADD_LIBRARY(toolkit-common STATIC common.c)
TARGET_LINK_LIBRARIES(toolkit-common)
ADD_LIBRARY(toolkit-common.${toolkit-common_VERSION_MAJOR} SHARED common.c)
TARGET_LINK_LIBRARIES(toolkit-common.${toolkit-common_VERSION_MAJOR})


include (InstallRequiredSystemLibraries)
SET (CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/License.txt")
SET (CPACK_PACKAGE_VERSION_MAJOR "${toolkit-common_VERSION_MAJOR}")
SET (CPACK_PACKAGE_VERSION_MINOR "${toolkit-common_VERSION_MINOR}")
SET (CPACK_PACKAGE_VERSION_PATCH "${toolkit-common_VERSION_PATCH}")
INCLUDE (CPack)
