PROJECT(octetos-toolkit-common-c++ VERSION 4.4.0 LANGUAGES ${LANG})

EXECUTE_PROCESS(COMMAND date +"%Y%m%d%H%M%S" OUTPUT_VARIABLE ${PROJECT_NAME}_VERSION_BUILD)
SET(${PROJECT_NAME}_VERSION_STAGE "snapshot")
SET(${PROJECT_NAME}_VERSION_NAME "reader")

SET(CMAKE_CXX_STANDARD 11)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)
SET(CMAKE_CXX_EXTENSIONS OFF)
CONFIGURE_FILE("${PROJECT_SOURCE_DIR}/versionInfo-c++.h.in" "${PROJECT_SOURCE_DIR}/versionInfo-c++.h")



FIND_PACKAGE(CUnit REQUIRED PATHS ${PROJECT_SOURCE_DIR}/../cmake/Modules/)
IF(CUNIT_FOUND)
	INCLUDE_DIRECTORIES(${CUNIT_INCLUDE_DIR})
ENDIF()


#ADD_LIBRARY(${PROJECT_NAME}-partial1 STATIC common.cpp)
#SET(LIBPARTIAL1 ${PROJECT_NAME}-partial1)
INCLUDE_DIRECTORIES(version-reader-c++ ${CMAKE_CURRENT_BINARY_DIR}/version-reader-c++)
#link_directories(version-reader-c++ ${CMAKE_CURRENT_BINARY_DIR}/version-reader-c++)
SET(LIBREADER "NULL")
ADD_SUBDIRECTORY(version-reader-c++)
#MESSAGE(STATUS "In common LIBREADER : " ${LIBREADER})


#[[ADD_LIBRARY(${PROJECT_NAME}  STATIC common.cpp common-parser.cpp)
ADD_DEPENDENCIES(${PROJECT_NAME} ${LIBREADER})
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${LIBREADER})]]

ADD_LIBRARY(${PROJECT_NAME}-obj  OBJECT common.cpp Error.cpp Object.cpp Version.cpp Version-parser.cpp Message.cpp Object.cpp)
#target_include_directories(${PROJECT_NAME}-obj PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>  $<INSTALL_INTERFACE:.> )
set_target_properties(${PROJECT_NAME}-obj  PROPERTIES POSITION_INDEPENDENT_CODE 1 )

#ADD_LIBRARY(${PROJECT_NAME}-obj2 SHARED $<TARGET_OBJECTS:${PROJECT_NAME}-obj> $<TARGET_OBJECTS:${LIBREADER}-obj>)
#target_include_directories(${PROJECT_NAME}   PUBLIC   $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>  $<INSTALL_INTERFACE:.> )
#add_library(${PROJECT_NAME} STATIC $<TARGET_OBJECTS:${PROJECT_NAME}-obj> $<TARGET_OBJECTS:${LIBREADER}-obj>)
#target_include_directories(${PROJECT_NAME}   PUBLIC   $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>  $<INSTALL_INTERFACE:.> )

ADD_LIBRARY(${PROJECT_NAME} SHARED $<TARGET_OBJECTS:${PROJECT_NAME}-obj> $<TARGET_OBJECTS:${LIBREADER}-obj>)
set_target_properties(${PROJECT_NAME}  PROPERTIES POSITION_INDEPENDENT_CODE 1 )
SET_TARGET_PROPERTIES(${PROJECT_NAME} PROPERTIES LINK_FLAGS -Wl,-Bsymbolic)
#TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${LIBREADER})

ADD_EXECUTABLE(testing-v${${PROJECT_NAME}_VERSION_MAJOR} tests/v${${PROJECT_NAME}_VERSION_MAJOR}.cc)
ADD_DEPENDENCIES(testing-v${${PROJECT_NAME}_VERSION_MAJOR} ${PROJECT_NAME})
#MESSAGE(STATUS "In common PROJECT_NAME : " ${PROJECT_NAME})
TARGET_LINK_LIBRARIES(testing-v${${PROJECT_NAME}_VERSION_MAJOR} ${CUNIT_LIBRARIES} ${PROJECT_NAME})

INSTALL(TARGETS ${PROJECT_NAME} DESTINATION lib/octetos/toolkit/common/)
INSTALL(FILES common.hpp DESTINATION include/octetos/toolkit/common/)


SET(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
INCLUDE (InstallRequiredSystemLibraries)
SET (CPACK_PACKAGE_VERSION_MAJOR "${${PROJECT_NAME}_VERSION_MAJOR}")
SET (CPACK_PACKAGE_VERSION_MINOR "${${PROJECT_NAME}_VERSION_MINOR}")
SET (CPACK_PACKAGE_VERSION_PATCH "${${PROJECT_NAME}_VERSION_PATCH}")
INCLUDE (CPack)
