# - Find mysqlclient
# Find the native MySQL includes and library
#
#  BUSINESSSERDB_INCLUDE_DIR - where to find Business.h, etc.
#  BUSINESSSERDB_LIBRARIES   - List of libraries when using Business Ser DB.
#  BUSINESSSERDB_FOUND       - True if business-serdb found.

IF (BUSINESS_COMMON_INCLUDE_DIR)
  # Already in cache, be silent
  SET(BUSINESS_COMMON_FIND_QUIETLY TRUE)
ENDIF (BUSINESS_COMMON_INCLUDE_DIR)

FIND_PATH(BUSINESS_COMMON_INCLUDE_DIR Business.hpp
  $ENV{HOME}/business/include/business
  /usr/local/include/business
  /usr/include/business
)

SET(BUSINESS_COMMON_NAMES business-common)
FIND_LIBRARY(BUSINESS_COMMON_LIBRARY
  NAMES ${BUSINESS_COMMON_NAMES}
  PATHS $ENV{HOME}/business/usr/lib /usr/lib /usr/local/lib /usr/lib/x86_64-linux-gnu
  PATH_SUFFIXES business
)

IF (BUSINESS_COMMON_INCLUDE_DIR AND BUSINESS_COMMON_LIBRARY)
  SET(BUSINESS_COMMON_FOUND TRUE)
  SET( BUSINESS_COMMON_LIBRARIES ${BUSINESS_COMMON_LIBRARY} )
ELSE (BUSINESS_COMMON_INCLUDE_DIR AND BUSINESS_COMMON_LIBRARY)
  SET(BUSINESS_COMMON_FOUND FALSE)
  SET( BUSINESS_COMMON_LIBRARIES )
ENDIF (BUSINESS_COMMON_INCLUDE_DIR AND BUSINESS_COMMON_LIBRARY)

IF (BUSINESS_COMMON_FOUND)
  IF (NOT BUSINESS_COMMON_FIND_QUIETLY)
    MESSAGE(STATUS "Found business-common: ${BUSINESS_COMMON_LIBRARY}")
  ENDIF (NOT BUSINESS_COMMON_FIND_QUIETLY)
ELSE (BUSINESS_COMMON_FOUND)
  IF (BUSINESS_COMMON_FIND_REQUIRED)
    MESSAGE(STATUS "Looked for business-common libraries named ${BUSINESS_COMMON_NAMES}.")
    MESSAGE(FATAL_ERROR "Could NOT find business-common library")
  ENDIF (BUSINESS_COMMON_FIND_REQUIRED)
ENDIF (BUSINESS_COMMON_FOUND)

MARK_AS_ADVANCED(
  BUSINESS_COMMON_LIBRARY
  BUSINESS_COMMON_INCLUDE_DIR
  )
